# Generated by Django 2.2.17 on 2021-04-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookCranny', '0002_book_time'),
        ('bookCranny', '0002_auto_20210402_1231'),
    ]

    operations = [
    ]
