# Generated by Django 2.2.17 on 2021-04-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookCranny', '0003_merge_20210403_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='blurb',
            new_name='description',
        ),
    ]
