# Generated by Django 2.2.17 on 2021-04-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookCranny', '0004_auto_20210403_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created time'),
        ),
    ]
