# Generated by Django 2.2.17 on 2021-04-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookCranny', '0006_auto_20210403_1948'),
        ('bookCranny', '0006_auto_20210404_1421'),
    ]

    operations = [
    ]
